<a href="https://colab.research.google.com/github/ArtemBaron/baron_vergeles/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
#tensor = многомерная матрица

In [3]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones([1,4,3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [11]:
 X = torch.Tensor([[1,  2,  3,  4],
                [5,  6,  7,  8],
                  [9, 10, 11, 12]])

In [14]:
X.shape

torch.Size([3, 4])

In [15]:
X.size()

torch.Size([3, 4])

In [16]:
Y = torch.Tensor([[11,  12,  13,  14],
                [5,  6,  7,  8],
                  [9, 10, 11, 12]])

In [17]:
X + Y

tensor([[12., 14., 16., 18.],
        [10., 12., 14., 16.],
        [18., 20., 22., 24.]])

In [25]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())
mask = X > 3
X[mask]

3


tensor([4, 5, 6, 7, 8, 9])

In [27]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = x
y[2] = torch.ones(3)

In [ ]:
y = x.clone()

In [28]:
x.dtype

torch.int64

In [29]:
x = x.double()

In [30]:
x.dtype

torch.float64

In [31]:
import numpy as np
x = np.array([[1,2,3,4], [5,6,7,8]])
x = torch.from_numpy(x)
x = x.numpy()

In [32]:
x = torch.rand([2,3])

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
# load the dataset, split into input (X) and output (y) variables
dataset = np.loadtxt('data.csv', delimiter=',')
X = dataset[:,0:8]
y = dataset[:,8]

In [3]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32).reshape(-1, 1)

In [5]:
X.shape

torch.Size([768, 8])

In [6]:
y.shape

torch.Size([768, 1])

In [7]:
model = nn.Sequential(
    nn.Linear(8, 12),
    nn.ReLU(),
    nn.Linear(12, 8),
    nn.ReLU(),
    nn.Linear(8, 1),
    nn.Sigmoid()
)

In [8]:
print(model)

Sequential(
  (0): Linear(in_features=8, out_features=12, bias=True)
  (1): ReLU()
  (2): Linear(in_features=12, out_features=8, bias=True)
  (3): ReLU()
  (4): Linear(in_features=8, out_features=1, bias=True)
  (5): Sigmoid()
)


In [9]:
class PimaClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden1 = nn.Linear(8, 12)
        self.act1 = nn.ReLU()
        self.hidden2 = nn.Linear(12, 8)
        self.act2 = nn.ReLU()
        self.output = nn.Linear(8, 1)
        self.act_output = nn.Sigmoid()

    def forward(self, x):
        x = self.act1(self.hidden1(x))
        x = self.act2(self.hidden2(x))
        x = self.act_output(self.output(x))
        return x

model = PimaClassifier()
print(model)

PimaClassifier(
  (hidden1): Linear(in_features=8, out_features=12, bias=True)
  (act1): ReLU()
  (hidden2): Linear(in_features=12, out_features=8, bias=True)
  (act2): ReLU()
  (output): Linear(in_features=8, out_features=1, bias=True)
  (act_output): Sigmoid()
)


In [10]:
loss_fn = nn.BCELoss()  # binary cross entropy
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [11]:
n_epochs = 100
batch_size = 10

for epoch in range(n_epochs):
    for i in range(0, len(X), batch_size):
        Xbatch = X[i:i+batch_size]
        y_pred = model(Xbatch)
        ybatch = y[i:i+batch_size]
        loss = loss_fn(y_pred, ybatch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f'Finished epoch {epoch}, latest loss {loss}')


Finished epoch 0, latest loss 0.6786960363388062
Finished epoch 1, latest loss 0.6189154386520386
Finished epoch 2, latest loss 0.5816575288772583
Finished epoch 3, latest loss 0.5569354295730591
Finished epoch 4, latest loss 0.530851423740387
Finished epoch 5, latest loss 0.5138074159622192
Finished epoch 6, latest loss 0.4954346716403961
Finished epoch 7, latest loss 0.47982534766197205
Finished epoch 8, latest loss 0.46523913741111755
Finished epoch 9, latest loss 0.45470815896987915
Finished epoch 10, latest loss 0.44575706124305725
Finished epoch 11, latest loss 0.4374169111251831
Finished epoch 12, latest loss 0.43054425716400146
Finished epoch 13, latest loss 0.4253319799900055
Finished epoch 14, latest loss 0.42101210355758667
Finished epoch 15, latest loss 0.4180966019630432
Finished epoch 16, latest loss 0.41547891497612
Finished epoch 17, latest loss 0.4126054048538208
Finished epoch 18, latest loss 0.411901593208313
Finished epoch 19, latest loss 0.41065412759780884
Finishe

In [12]:

# compute accuracy (no_grad is optional)
with torch.no_grad():
    y_pred = model(X)

accuracy = (y_pred.round() == y).float().mean()
print(f"Accuracy {accuracy}")

Accuracy 0.7591145634651184


In [13]:

# make probability predictions with the model
predictions = model(X)
# round predictions
rounded = predictions.round()

In [14]:
# make class predictions with the model
predictions = (model(X) > 0.5).int()

In [15]:
predictions

tensor([[1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],

In [ ]:
b

In [ ]:
b

In [ ]:
b